branches:
  - main

tagFormat: "${version}"

plugins:
  - '@semantic-release/commit-analyzer'
  - 'semantic-release-commitlint'
  -
    - "@semantic-release/release-notes-generator"
    - preset: "conventionalcommits"
  -
    - "@semantic-release/git"
    - assets: []
      messsage: false
  -
    - "@semantic-release/github"
    - successComment: false
      failComment: false
  -
    - '@eshepelyuk/semantic-release-helm-oci'
    - registry: oci://ghcr.io/schemahero/helm
      skipAppVersion: true

