branches:
  - main

tagFormat: "${version}"

preset: "conventionalcommits"

plugins:
  - '@semantic-release/commit-analyzer'
  -
    - "@semantic-release/release-notes-generator"
    - host: "https://github.com"
  -
    - "@semantic-release/git"
    - assets: []
      messsage: false
  -
    - "@semantic-release/github"
    - successComment: false
      failComment: false
  -
    - "@semantic-release/exec"
    - verifyConditionsCmd: "rm -rf *.tgz"
      prepareCmd: "helm package --version ${nextRelease.version} ."
      publishCmd: "helm push schemahero-${nextRelease.version}.tgz oci://ghcr.io/schemahero/helm"
